# Generated by Django 6.0.2 on 2026-02-23 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='vendedor',
            field=models.OneToOneField(help_text='Usuario vendedor asociado a esta tienda', limit_choices_to={'tipo_usuario__in': ['vendedor', 'ambos']}, on_delete=django.db.models.deletion.CASCADE, related_name='tienda', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('comprador', 'Comprador'), ('vendedor', 'Vendedor'), ('ambos', 'Comprador y Vendedor')], default='comprador', help_text='Indica si el usuario es comprador, vendedor o ambos', max_length=10),
        ),
    ]
