# Generated by Django 6.0.2 on 2026-02-22 20:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kilometraje', models.IntegerField(help_text='Kilómetros recorridos')),
                ('ubicacion', models.CharField(help_text='Ciudad o zona', max_length=100)),
                ('tipo_combustible', models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diésel'), ('hibrido', 'Híbrido'), ('electrico', 'Eléctrico')], max_length=20)),
                ('transmision', models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática'), ('semiautomatica', 'Semiautomática')], max_length=20)),
                ('cilindrada', models.CharField(blank=True, help_text='Ej: 1.6L, 2.0L', max_length=10)),
                ('potencia', models.IntegerField(blank=True, help_text='Caballos de fuerza (CV)', null=True)),
                ('num_puertas', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('num_plazas', models.IntegerField()),
                ('carroceria', models.CharField(blank=True, choices=[('sedan', 'Sedán'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('familiar', 'Familiar'), ('coupe', 'Coupé'), ('convertible', 'Convertible'), ('monovolumen', 'Monovolumen'), ('pickup', 'Pickup')], max_length=30)),
                ('traccion', models.CharField(blank=True, choices=[('delantera', 'Delantera'), ('trasera', 'Trasera'), ('4x4', '4x4 / Integral')], max_length=20)),
                ('direccion_asistida', models.BooleanField(default=True)),
                ('aire_acondicionado', models.BooleanField(default=True)),
                ('abs', models.BooleanField(default=True)),
                ('airbags', models.IntegerField(blank=True, null=True)),
                ('garantia', models.CharField(blank=True, help_text='Ej: 6 meses, 1 año', max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=1000)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='coches/')),
                ('activo', models.BooleanField(default=True, help_text='Aprobado por administrador')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('destacado', models.BooleanField(default=False, help_text='Anuncio destacado (requiere pago)')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coches', to='accounts.tienda')),
            ],
            options={
                'verbose_name': 'Coche',
                'verbose_name_plural': 'Coches',
            },
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kilometraje', models.IntegerField(help_text='Kilómetros recorridos')),
                ('ubicacion', models.CharField(max_length=100)),
                ('tipo_moto', models.CharField(blank=True, choices=[('scooter', 'Scooter'), ('naked', 'Naked'), ('deportiva', 'Deportiva'), ('cruiser', 'Cruiser'), ('touring', 'Touring'), ('enduro', 'Enduro'), ('motocross', 'Motocross'), ('cafe_racer', 'Café Racer')], max_length=30)),
                ('cilindrada', models.CharField(help_text='Ej: 125cc, 600cc', max_length=10)),
                ('potencia', models.IntegerField(blank=True, help_text='Caballos de fuerza (CV)', null=True)),
                ('tipo_motor', models.CharField(blank=True, help_text='Ej: 2T, 4T, monocilíndrico, bicilíndrico', max_length=30)),
                ('refrigeracion', models.CharField(blank=True, help_text='Aire, líquida', max_length=30)),
                ('arranque', models.CharField(blank=True, choices=[('electrico', 'Eléctrico'), ('patada', 'Patada'), ('ambos', 'Ambos')], max_length=20)),
                ('cambio', models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatico', 'Automático')], max_length=20)),
                ('num_marchas', models.IntegerField(blank=True, null=True)),
                ('freno_delantera', models.CharField(blank=True, help_text='Disco, tambor', max_length=30)),
                ('freno_trasera', models.CharField(blank=True, help_text='Disco, tambor', max_length=30)),
                ('abs', models.BooleanField(default=False)),
                ('capacidad_tanque', models.DecimalField(blank=True, decimal_places=1, help_text='Litros', max_digits=4, null=True)),
                ('peso', models.IntegerField(blank=True, help_text='kg', null=True)),
                ('color', models.CharField(max_length=30)),
                ('garantia', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=1000)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='motos/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('destacado', models.BooleanField(default=False)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motos', to='accounts.tienda')),
            ],
            options={
                'verbose_name': 'Moto',
                'verbose_name_plural': 'Motos',
            },
        ),
    ]
