# Generated by Django 6.0.2 on 2026-02-23 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('coche', 'Coche'), ('moto', 'Moto')], default='coche', max_length=10)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.AlterField(
            model_name='coche',
            name='marca',
            field=models.ForeignKey(limit_choices_to={'tipo': 'coche'}, on_delete=django.db.models.deletion.PROTECT, related_name='coches', to='vehiculos.marca'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='marca',
            field=models.ForeignKey(limit_choices_to={'tipo': 'moto'}, on_delete=django.db.models.deletion.PROTECT, related_name='motos', to='vehiculos.marca'),
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('coche', 'Coche'), ('moto', 'Moto')], default='coche', max_length=10)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='vehiculos.marca')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'unique_together': {('marca', 'nombre')},
            },
        ),
        migrations.AlterField(
            model_name='coche',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coches', to='vehiculos.modelo'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motos', to='vehiculos.modelo'),
        ),
    ]
