# Generated by Django 6.0.2 on 2026-02-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_marca_alter_coche_marca_alter_moto_marca_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='marca',
            unique_together={('nombre', 'tipo')},
        ),
    ]
