# Generated by hand for Django 6.x (container cannot install Django 6.x).

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_tienda_vendedor_alter_usuario_tipo_usuario'),
        ('vehiculos', '0004_alter_marca_nombre_alter_marca_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='activo',
            field=models.BooleanField(default=False, help_text='Aprobado por administrador'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='activo',
            field=models.BooleanField(default=False),
        ),

        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(choices=[('coche', 'Coche'), ('moto', 'Moto')], max_length=10)),
                ('vehiculo_id', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('mensaje', models.TextField(blank=True, max_length=2000)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('en_contacto', 'En contacto'), ('cerrado', 'Cerrado'), ('descartado', 'Descartado')], default='nuevo', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_enviados', to=settings.AUTH_USER_MODEL)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='accounts.tienda')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
            },
        ),

        migrations.CreateModel(
            name='PlataformaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tarifa_publicacion_cents', models.PositiveIntegerField(default=0, help_text='0 = gratis')),
                ('tarifa_destacado_cents', models.PositiveIntegerField(default=1000, help_text='en centavos')),
                ('moneda', models.CharField(default='eur', max_length=10)),
                ('auto_aprobar_listados', models.BooleanField(default=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de plataforma',
                'verbose_name_plural': 'Configuración de plataforma',
            },
        ),

        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('publicacion', 'Tarifa de publicación'), ('destacado', 'Destacado')], max_length=20)),
                ('tipo_vehiculo', models.CharField(choices=[('coche', 'Coche'), ('moto', 'Moto')], max_length=10)),
                ('vehiculo_id', models.PositiveIntegerField()),
                ('moneda', models.CharField(default='eur', max_length=10)),
                ('monto_cents', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('creada', 'Creada'), ('pagada', 'Pagada'), ('fallida', 'Fallida'), ('reembolsada', 'Reembolsada')], default='creada', max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pagado_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción de pago',
                'verbose_name_plural': 'Transacciones de pago',
            },
        ),

        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=255)),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento Stripe',
                'verbose_name_plural': 'Eventos Stripe',
            },
        ),

        # Indexes Lead
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tienda', 'estado', 'creado_en'], name='lead_tienda_estado_creado_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tipo_vehiculo', 'vehiculo_id'], name='lead_tipo_vehiculo_id_idx'),
        ),

        # Indexes PaymentTransaction
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['stripe_session_id'], name='pay_stripe_session_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['tipo_vehiculo', 'vehiculo_id'], name='pay_tipo_vehiculo_id_idx'),
        ),

        # Indexes Coche
        migrations.AddIndex(
            model_name='coche',
            index=models.Index(fields=['activo', 'destacado', 'fecha_publicacion'], name='coche_act_dest_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='coche',
            index=models.Index(fields=['precio'], name='coche_precio_idx'),
        ),
        migrations.AddIndex(
            model_name='coche',
            index=models.Index(fields=['anio'], name='coche_anio_idx'),
        ),
        migrations.AddIndex(
            model_name='coche',
            index=models.Index(fields=['kilometraje'], name='coche_km_idx'),
        ),
        migrations.AddIndex(
            model_name='coche',
            index=models.Index(fields=['ubicacion'], name='coche_ubicacion_idx'),
        ),
        migrations.AddIndex(
            model_name='coche',
            index=models.Index(fields=['marca', 'modelo'], name='coche_marca_modelo_idx'),
        ),

        # Indexes Moto
        migrations.AddIndex(
            model_name='moto',
            index=models.Index(fields=['activo', 'destacado', 'fecha_publicacion'], name='moto_act_dest_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='moto',
            index=models.Index(fields=['precio'], name='moto_precio_idx'),
        ),
        migrations.AddIndex(
            model_name='moto',
            index=models.Index(fields=['anio'], name='moto_anio_idx'),
        ),
        migrations.AddIndex(
            model_name='moto',
            index=models.Index(fields=['kilometraje'], name='moto_km_idx'),
        ),
        migrations.AddIndex(
            model_name='moto',
            index=models.Index(fields=['ubicacion'], name='moto_ubicacion_idx'),
        ),
        migrations.AddIndex(
            model_name='moto',
            index=models.Index(fields=['marca', 'modelo'], name='moto_marca_modelo_idx'),
        ),
    ]
